[package]
name = "git-rust-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.3"
git2 = "0.18.3"
inquire = "0.7.2"
log = "0.4.21"
seahorse = "2.2.0"
